name: App version Guard

on:
  pull_request:
    branches: [ "main", "master" ]
    types: [opened, edited, synchronize, reopened]

  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Block if the versions are not matched
      run: |
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
        if echo "$changed_files" | grep -q 'package.json'; then
          echo "package.json was modified. Proceeding with further steps."
          node ./scripts/index.mjs
        else
          echo "No changes to package.json. Skipping further steps."
        fi
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}