name: App version Guard

on:
  pull_request:
    branches: [ "main", "master" ]
    types: [opened, edited, synchronize, reopened]

   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v4
    - name: Block if the versions are not matched
      run: |
        node ./scripts/index.mjs
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}