name: App version Guard

on:
  pull_request:
    branches: [ "main", "master" ]
    types: [opened, edited, synchronize, reopened]

   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Block if the versions are not matched
      run: node ../scripts/versions/app-version-check.mjs
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}